ALTER TABLE `invoice` ADD INDEX `CUS_CODEX` (`CUS_CODE`);

ALTER TABLE `line` ADD INDEX `INV_NUMBER` (`INV_NUMBER`);
ALTER TABLE `line` ADD INDEX `P-CODE` (`PROD_CODE`);

ALTER TABLE `product` ADD COLUMN `P_INDATE` DATE NOT NULL;
ALTER TABLE `product` ADD INDEX `P_INDATEX` (`P_INDATE`);

CREATE INDEX `VENPRODX` ON product(`VEND_CODE`, `PROD_CODE`);
CREATE INDEX `PROD_PRICEX` ON product(`PROD_PRICE` DESC);

ALTER TABLE product DROP INDEX `PROD_PRICEX`;