# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reception.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReceptionWindow(object):
    def setupUi(self, ReceptionWindow):
        ReceptionWindow.setObjectName("ReceptionWindow")
        ReceptionWindow.resize(621, 661)
        ReceptionWindow.setToolTipDuration(-59)
        self.centralwidget = QtWidgets.QWidget(ReceptionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.lineEditCusID = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCusID.sizePolicy().hasHeightForWidth())
        self.lineEditCusID.setSizePolicy(sizePolicy)
        self.lineEditCusID.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditCusID.setObjectName("lineEditCusID")
        self.horizontalLayout_6.addWidget(self.lineEditCusID)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.btnCreateOrder = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateOrder.setObjectName("btnCreateOrder")
        self.verticalLayout_7.addWidget(self.btnCreateOrder)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEditOrderID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditOrderID.setObjectName("lineEditOrderID")
        self.horizontalLayout_8.addWidget(self.lineEditOrderID)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.selectHotelPlace = QtWidgets.QComboBox(self.centralwidget)
        self.selectHotelPlace.setObjectName("selectHotelPlace")
        self.verticalLayout_7.addWidget(self.selectHotelPlace)
        self.selectRoomType = QtWidgets.QComboBox(self.centralwidget)
        self.selectRoomType.setObjectName("selectRoomType")
        self.verticalLayout_7.addWidget(self.selectRoomType)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.dateTimeEditCheckIn = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEditCheckIn.setObjectName("dateTimeEditCheckIn")
        self.horizontalLayout_9.addWidget(self.dateTimeEditCheckIn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.dateTimeEditCheckOut = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEditCheckOut.setObjectName("dateTimeEditCheckOut")
        self.horizontalLayout_10.addWidget(self.dateTimeEditCheckOut)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.btnFindAvailableRooms = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindAvailableRooms.setObjectName("btnFindAvailableRooms")
        self.verticalLayout_7.addWidget(self.btnFindAvailableRooms)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.selectAvailableRoom = QtWidgets.QComboBox(self.centralwidget)
        self.selectAvailableRoom.setObjectName("selectAvailableRoom")
        self.horizontalLayout_11.addWidget(self.selectAvailableRoom)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.btnAddRoomToOrder = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddRoomToOrder.setObjectName("btnAddRoomToOrder")
        self.verticalLayout_7.addWidget(self.btnAddRoomToOrder)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_7.addWidget(self.lineEdit_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        ReceptionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReceptionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 22))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setObjectName("menubar")
        self.menuB_kanir = QtWidgets.QMenu(self.menubar)
        self.menuB_kanir.setObjectName("menuB_kanir")
        ReceptionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReceptionWindow)
        self.statusbar.setObjectName("statusbar")
        ReceptionWindow.setStatusBar(self.statusbar)
        self.actionBoka = QtWidgets.QAction(ReceptionWindow)
        self.actionBoka.setObjectName("actionBoka")
        self.actionSja_bokanir = QtWidgets.QAction(ReceptionWindow)
        self.actionSja_bokanir.setObjectName("actionSja_bokanir")
        self.menuB_kanir.addAction(self.actionBoka)
        self.menuB_kanir.addAction(self.actionSja_bokanir)
        self.menubar.addAction(self.menuB_kanir.menuAction())

        self.retranslateUi(ReceptionWindow)
        self.selectHotelPlace.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ReceptionWindow)

    def retranslateUi(self, ReceptionWindow):
        _translate = QtCore.QCoreApplication.translate
        ReceptionWindow.setWindowTitle(_translate("ReceptionWindow", "Hraun Hótel - Móttökuritari"))
        self.label_3.setText(_translate("ReceptionWindow", "Panta"))
        self.label_8.setText(_translate("ReceptionWindow", "Pöntunarnúmer: "))
        self.label.setText(_translate("ReceptionWindow", "CusID"))
        self.btnCreateOrder.setText(_translate("ReceptionWindow", "Búa til nýja pöntun"))
        self.label_7.setText(_translate("ReceptionWindow", "Bæta herbergi við pöntun"))
        self.label_9.setText(_translate("ReceptionWindow", "OrderID"))
        self.label_11.setText(_translate("ReceptionWindow", "CheckIn"))
        self.label_12.setText(_translate("ReceptionWindow", "CheckOut"))
        self.btnFindAvailableRooms.setText(_translate("ReceptionWindow", "Finna laus herbergi"))
        self.label_13.setText(_translate("ReceptionWindow", "Room"))
        self.btnAddRoomToOrder.setText(_translate("ReceptionWindow", "Bæta herbergi við pöntun"))
        self.label_2.setText(_translate("ReceptionWindow", "Sjá pantanir"))
        self.label_6.setText(_translate("ReceptionWindow", "TextLabel"))
        self.label_4.setText(_translate("ReceptionWindow", "TextLabel"))
        self.menuB_kanir.setTitle(_translate("ReceptionWindow", "Bókanir"))
        self.actionBoka.setText(_translate("ReceptionWindow", "Bóka"))
        self.actionSja_bokanir.setText(_translate("ReceptionWindow", "Sjá bókanir"))

