# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesignerProject/reception.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReceptionWindow(object):
    def setupUi(self, ReceptionWindow):
        ReceptionWindow.setObjectName("ReceptionWindow")
        ReceptionWindow.setWindowModality(QtCore.Qt.NonModal)
        ReceptionWindow.resize(570, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReceptionWindow.sizePolicy().hasHeightForWidth())
        ReceptionWindow.setSizePolicy(sizePolicy)
        ReceptionWindow.setMinimumSize(QtCore.QSize(570, 420))
        ReceptionWindow.setMaximumSize(QtCore.QSize(570, 420))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/hotel_and_services/png/briefcase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReceptionWindow.setWindowIcon(icon)
        ReceptionWindow.setStyleSheet("QFrame#frame, QFrame#frame_2 {\n"
"background-color: #3F4045;\n"
"color: #fff;\n"
"border: none;\n"
"}\n"
"\n"
"QToolButton#toolButton, QToolButton#toolButton_2, QToolButton#toolButton_3, QToolButton#toolButton_4, QToolButton#toolButton_5, QToolButton#toolButton_6 {\n"
"background-color: #7BB2D9;\n"
"border-radius: 7px;\n"
"color: #3F4045;\n"
"}\n"
"\n"
"#frame QToolButton:checked, #frame QToolButton:pressed, #frame QToolButton:hover {\n"
"color: #fff;\n"
"}\n"
"QLabel#labelTopName, QLabel#labelTopTitle {\n"
"color: #fff;\n"
"}\n"
"QVBoxLayout#verticalLayout_5 {\n"
"border-bottom: 1px solid #000;\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"QLabel#labelBorder, QLabel#labelBorder_2, QLabel#labelBorder_3, QLabel#labelBorder_4, QLabel#labelBorder_5, QLabel#labelBorder_6 {\n"
"border-top: 1px solid rgba(0,0,0,0.2);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ReceptionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, 49, 101, 381))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 381))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(20, 10, 51, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/hotel_and_services/png/reception.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(32, 32))
        self.toolButton.setCheckable(True)
        self.toolButton.setChecked(True)
        self.toolButton.setAutoExclusive(True)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(20, 70, 51, 51))
        self.toolButton_2.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/hotel_and_services/png/room-key-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setCheckable(True)
        self.toolButton_2.setAutoExclusive(True)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(20, 130, 51, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/hotel_and_services/png/notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_3.setCheckable(True)
        self.toolButton_3.setAutoExclusive(True)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        self.toolButton_4.setGeometry(QtCore.QRect(20, 190, 51, 51))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/hotel_and_services/png/notebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon4)
        self.toolButton_4.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_4.setCheckable(True)
        self.toolButton_4.setAutoExclusive(True)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        self.toolButton_5.setGeometry(QtCore.QRect(20, 250, 51, 51))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/hotel_and_services/png/woman.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_5.setCheckable(True)
        self.toolButton_5.setAutoExclusive(True)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setObjectName("toolButton_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(100, 50, 471, 381))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btnCreateOrder = QtWidgets.QPushButton(self.page)
        self.btnCreateOrder.setGeometry(QtCore.QRect(315, 294, 101, 31))
        self.btnCreateOrder.setObjectName("btnCreateOrder")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 231, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(20, -1, -1, 20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.lineEditNewOrderCusSSN = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditNewOrderCusSSN.setObjectName("lineEditNewOrderCusSSN")
        self.verticalLayout_8.addWidget(self.lineEditNewOrderCusSSN, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 231, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, -1, -1, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignLeft)
        self.lineEditOrderID = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEditOrderID.setObjectName("lineEditOrderID")
        self.verticalLayout_2.addWidget(self.lineEditOrderID, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 70, 231, 64))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.selectHotelPlace = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.selectHotelPlace.setObjectName("selectHotelPlace")
        self.verticalLayout_3.addWidget(self.selectHotelPlace, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 140, 231, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10, 0, QtCore.Qt.AlignLeft)
        self.selectRoomType = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.selectRoomType.setObjectName("selectRoomType")
        self.verticalLayout_4.addWidget(self.selectRoomType, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 210, 231, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.dateTimeEditCheckIn = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_6)
        self.dateTimeEditCheckIn.setObjectName("dateTimeEditCheckIn")
        self.verticalLayout_5.addWidget(self.dateTimeEditCheckIn, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 280, 231, 61))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.dateTimeEditCheckOut = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_7)
        self.dateTimeEditCheckOut.setObjectName("dateTimeEditCheckOut")
        self.verticalLayout_6.addWidget(self.dateTimeEditCheckOut, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(230, 70, 231, 64))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9, 0, QtCore.Qt.AlignRight)
        self.selectAvailableRoom = QtWidgets.QComboBox(self.horizontalLayoutWidget_8)
        self.selectAvailableRoom.setObjectName("selectAvailableRoom")
        self.verticalLayout_7.addWidget(self.selectAvailableRoom, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(230, 10, 231, 61))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 20, 20)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnFindAvailableRooms = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.btnFindAvailableRooms.setObjectName("btnFindAvailableRooms")
        self.horizontalLayout_9.addWidget(self.btnFindAvailableRooms, 0, QtCore.Qt.AlignRight)
        self.btnAddRoomToOrder = QtWidgets.QPushButton(self.page_3)
        self.btnAddRoomToOrder.setGeometry(QtCore.QRect(275, 294, 141, 31))
        self.btnAddRoomToOrder.setObjectName("btnAddRoomToOrder")
        self.labelBorder = QtWidgets.QLabel(self.page_3)
        self.labelBorder.setGeometry(QtCore.QRect(-2, 70, 461, 2))
        self.labelBorder.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder.setText("")
        self.labelBorder.setObjectName("labelBorder")
        self.labelBorder_2 = QtWidgets.QLabel(self.page_3)
        self.labelBorder_2.setGeometry(QtCore.QRect(-3, 140, 461, 2))
        self.labelBorder_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder_2.setText("")
        self.labelBorder_2.setObjectName("labelBorder_2")
        self.labelBorder_3 = QtWidgets.QLabel(self.page_3)
        self.labelBorder_3.setGeometry(QtCore.QRect(-3, 210, 151, 2))
        self.labelBorder_3.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder_3.setText("")
        self.labelBorder_3.setObjectName("labelBorder_3")
        self.labelBorder_4 = QtWidgets.QLabel(self.page_3)
        self.labelBorder_4.setGeometry(QtCore.QRect(-3, 280, 151, 2))
        self.labelBorder_4.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder_4.setText("")
        self.labelBorder_4.setObjectName("labelBorder_4")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 9, 231, 23))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegFName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEditCusRegFName.setObjectName("lineEditCusRegFName")
        self.horizontalLayout_10.addWidget(self.lineEditCusRegFName, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(0, 30, 231, 23))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegLName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_17)
        self.lineEditCusRegLName.setObjectName("lineEditCusRegLName")
        self.horizontalLayout_17.addWidget(self.lineEditCusRegLName, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(0, 50, 231, 23))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_18.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegSSN = QtWidgets.QLineEdit(self.horizontalLayoutWidget_18)
        self.lineEditCusRegSSN.setObjectName("lineEditCusRegSSN")
        self.horizontalLayout_18.addWidget(self.lineEditCusRegSSN, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 70, 231, 23))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegEmail = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.lineEditCusRegEmail.setObjectName("lineEditCusRegEmail")
        self.horizontalLayout_11.addWidget(self.lineEditCusRegEmail, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(0, 90, 231, 23))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegPhone = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.lineEditCusRegPhone.setObjectName("lineEditCusRegPhone")
        self.horizontalLayout_12.addWidget(self.lineEditCusRegPhone, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(0, 130, 231, 23))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegCountry = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.lineEditCusRegCountry.setObjectName("lineEditCusRegCountry")
        self.horizontalLayout_13.addWidget(self.lineEditCusRegCountry, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(0, 150, 231, 23))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegCity = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.lineEditCusRegCity.setObjectName("lineEditCusRegCity")
        self.horizontalLayout_14.addWidget(self.lineEditCusRegCity, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(0, 170, 231, 23))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_15.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegZip = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.lineEditCusRegZip.setObjectName("lineEditCusRegZip")
        self.horizontalLayout_15.addWidget(self.lineEditCusRegZip, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(0, 190, 231, 23))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegStreet = QtWidgets.QLineEdit(self.horizontalLayoutWidget_16)
        self.lineEditCusRegStreet.setObjectName("lineEditCusRegStreet")
        self.horizontalLayout_16.addWidget(self.lineEditCusRegStreet, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(0, 210, 231, 23))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_19.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegBuildingNum = QtWidgets.QLineEdit(self.horizontalLayoutWidget_19)
        self.lineEditCusRegBuildingNum.setObjectName("lineEditCusRegBuildingNum")
        self.horizontalLayout_19.addWidget(self.lineEditCusRegBuildingNum, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(0, 230, 231, 23))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_20.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_20)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegApartNum = QtWidgets.QLineEdit(self.horizontalLayoutWidget_20)
        self.lineEditCusRegApartNum.setObjectName("lineEditCusRegApartNum")
        self.horizontalLayout_20.addWidget(self.lineEditCusRegApartNum, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(0, 270, 231, 23))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.horizontalLayout_21.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_21)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegUser = QtWidgets.QLineEdit(self.horizontalLayoutWidget_21)
        self.lineEditCusRegUser.setObjectName("lineEditCusRegUser")
        self.horizontalLayout_21.addWidget(self.lineEditCusRegUser, 0, QtCore.Qt.AlignRight)
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(0, 290, 231, 23))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_22.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_22)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22, 0, QtCore.Qt.AlignLeft)
        self.lineEditCusRegPassword = QtWidgets.QLineEdit(self.horizontalLayoutWidget_22)
        self.lineEditCusRegPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditCusRegPassword.setObjectName("lineEditCusRegPassword")
        self.horizontalLayout_22.addWidget(self.lineEditCusRegPassword, 0, QtCore.Qt.AlignRight)
        self.btnRegCus = QtWidgets.QPushButton(self.page_4)
        self.btnRegCus.setGeometry(QtCore.QRect(315, 294, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegCus.sizePolicy().hasHeightForWidth())
        self.btnRegCus.setSizePolicy(sizePolicy)
        self.btnRegCus.setMinimumSize(QtCore.QSize(0, 0))
        self.btnRegCus.setObjectName("btnRegCus")
        self.labelBorder_5 = QtWidgets.QLabel(self.page_4)
        self.labelBorder_5.setGeometry(QtCore.QRect(-3, 120, 233, 2))
        self.labelBorder_5.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder_5.setText("")
        self.labelBorder_5.setObjectName("labelBorder_5")
        self.labelBorder_6 = QtWidgets.QLabel(self.page_4)
        self.labelBorder_6.setGeometry(QtCore.QRect(-3, 260, 233, 2))
        self.labelBorder_6.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder_6.setText("")
        self.labelBorder_6.setObjectName("labelBorder_6")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.treeCustHistory = QtWidgets.QTreeWidget(self.page_5)
        self.treeCustHistory.setGeometry(QtCore.QRect(50, 90, 361, 192))
        self.treeCustHistory.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeCustHistory.setAllColumnsShowFocus(False)
        self.treeCustHistory.setHeaderHidden(False)
        self.treeCustHistory.setObjectName("treeCustHistory")
        self.treeCustHistory.headerItem().setText(0, "1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 10, 471, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.lineEditCusHistorySearchSSN = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditCusHistorySearchSSN.setObjectName("lineEditCusHistorySearchSSN")
        self.verticalLayout_9.addWidget(self.lineEditCusHistorySearchSSN, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.btnSearchCusHistory = QtWidgets.QPushButton(self.page_5)
        self.btnSearchCusHistory.setGeometry(QtCore.QRect(315, 294, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearchCusHistory.sizePolicy().hasHeightForWidth())
        self.btnSearchCusHistory.setSizePolicy(sizePolicy)
        self.btnSearchCusHistory.setMinimumSize(QtCore.QSize(0, 0))
        self.btnSearchCusHistory.setObjectName("btnSearchCusHistory")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayoutWidget_24 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_24.setGeometry(QtCore.QRect(0, 186, 471, 23))
        self.horizontalLayoutWidget_24.setObjectName("horizontalLayoutWidget_24")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_24)
        self.horizontalLayout_37.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.labelAboutWorkplaces = QtWidgets.QLabel(self.horizontalLayoutWidget_24)
        self.labelAboutWorkplaces.setObjectName("labelAboutWorkplaces")
        self.horizontalLayout_37.addWidget(self.labelAboutWorkplaces, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayoutWidget_25 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_25.setGeometry(QtCore.QRect(0, 120, 471, 23))
        self.horizontalLayoutWidget_25.setObjectName("horizontalLayoutWidget_25")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_25)
        self.horizontalLayout_38.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.labelAboutPhone = QtWidgets.QLabel(self.horizontalLayoutWidget_25)
        self.labelAboutPhone.setObjectName("labelAboutPhone")
        self.horizontalLayout_38.addWidget(self.labelAboutPhone, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayoutWidget_27 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_27.setGeometry(QtCore.QRect(0, 98, 471, 23))
        self.horizontalLayoutWidget_27.setObjectName("horizontalLayoutWidget_27")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_27)
        self.horizontalLayout_40.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.labelAboutEmail = QtWidgets.QLabel(self.horizontalLayoutWidget_27)
        self.labelAboutEmail.setObjectName("labelAboutEmail")
        self.horizontalLayout_40.addWidget(self.labelAboutEmail, 0, QtCore.Qt.AlignLeft)
        self.labelBorder_7 = QtWidgets.QLabel(self.page_6)
        self.labelBorder_7.setGeometry(QtCore.QRect(-3, 120, 233, 2))
        self.labelBorder_7.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder_7.setText("")
        self.labelBorder_7.setObjectName("labelBorder_7")
        self.horizontalLayoutWidget_28 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_28.setGeometry(QtCore.QRect(0, 32, 471, 23))
        self.horizontalLayoutWidget_28.setObjectName("horizontalLayoutWidget_28")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_28)
        self.horizontalLayout_41.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.labelAboutName = QtWidgets.QLabel(self.horizontalLayoutWidget_28)
        self.labelAboutName.setObjectName("labelAboutName")
        self.horizontalLayout_41.addWidget(self.labelAboutName, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayoutWidget_30 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_30.setGeometry(QtCore.QRect(0, 76, 471, 23))
        self.horizontalLayoutWidget_30.setObjectName("horizontalLayoutWidget_30")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_30)
        self.horizontalLayout_43.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.labelAboutSSN = QtWidgets.QLabel(self.horizontalLayoutWidget_30)
        self.labelAboutSSN.setObjectName("labelAboutSSN")
        self.horizontalLayout_43.addWidget(self.labelAboutSSN, 0, QtCore.Qt.AlignLeft)
        self.labelBorder_8 = QtWidgets.QLabel(self.page_6)
        self.labelBorder_8.setGeometry(QtCore.QRect(-3, 260, 233, 2))
        self.labelBorder_8.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelBorder_8.setText("")
        self.labelBorder_8.setObjectName("labelBorder_8")
        self.horizontalLayoutWidget_32 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_32.setGeometry(QtCore.QRect(0, 142, 471, 23))
        self.horizontalLayoutWidget_32.setObjectName("horizontalLayoutWidget_32")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_32)
        self.horizontalLayout_45.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.labelAboutAddress = QtWidgets.QLabel(self.horizontalLayoutWidget_32)
        self.labelAboutAddress.setObjectName("labelAboutAddress")
        self.horizontalLayout_45.addWidget(self.labelAboutAddress, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayoutWidget_35 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_35.setGeometry(QtCore.QRect(0, 164, 471, 23))
        self.horizontalLayoutWidget_35.setObjectName("horizontalLayoutWidget_35")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_35)
        self.horizontalLayout_48.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.labelAboutUser = QtWidgets.QLabel(self.horizontalLayoutWidget_35)
        self.labelAboutUser.setObjectName("labelAboutUser")
        self.horizontalLayout_48.addWidget(self.labelAboutUser, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayoutWidget_36 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_36.setGeometry(QtCore.QRect(0, 54, 471, 23))
        self.horizontalLayoutWidget_36.setObjectName("horizontalLayoutWidget_36")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_36)
        self.horizontalLayout_49.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.labelAboutTitle = QtWidgets.QLabel(self.horizontalLayoutWidget_36)
        self.labelAboutTitle.setObjectName("labelAboutTitle")
        self.horizontalLayout_49.addWidget(self.labelAboutTitle, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayoutWidget_29 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_29.setGeometry(QtCore.QRect(0, 10, 471, 23))
        self.horizontalLayoutWidget_29.setObjectName("horizontalLayoutWidget_29")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_29)
        self.horizontalLayout_42.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.labelAboutID = QtWidgets.QLabel(self.horizontalLayoutWidget_29)
        self.labelAboutID.setObjectName("labelAboutID")
        self.horizontalLayout_42.addWidget(self.labelAboutID, 0, QtCore.Qt.AlignLeft)
        self.stackedWidget.addWidget(self.page_6)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 571, 51))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 171, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTopTitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTopTitle.setFont(font)
        self.labelTopTitle.setObjectName("labelTopTitle")
        self.horizontalLayout.addWidget(self.labelTopTitle, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(169, -1, 401, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTopName = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelTopName.setFont(font)
        self.labelTopName.setObjectName("labelTopName")
        self.verticalLayout.addWidget(self.labelTopName, 0, QtCore.Qt.AlignHCenter)
        ReceptionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReceptionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 22))
        self.menubar.setObjectName("menubar")
        self.menuForrit = QtWidgets.QMenu(self.menubar)
        self.menuForrit.setObjectName("menuForrit")
        ReceptionWindow.setMenuBar(self.menubar)
        self.actionSkra_ut = QtWidgets.QAction(ReceptionWindow)
        self.actionSkra_ut.setObjectName("actionSkra_ut")
        self.actionH_tta = QtWidgets.QAction(ReceptionWindow)
        self.actionH_tta.setObjectName("actionH_tta")
        self.menuForrit.addAction(self.actionSkra_ut)
        self.menuForrit.addAction(self.actionH_tta)
        self.menubar.addAction(self.menuForrit.menuAction())

        self.retranslateUi(ReceptionWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ReceptionWindow)

    def retranslateUi(self, ReceptionWindow):
        _translate = QtCore.QCoreApplication.translate
        ReceptionWindow.setWindowTitle(_translate("ReceptionWindow", "Hraun Hótel - Móttökuritari"))
        self.toolButton.setText(_translate("ReceptionWindow", "Panta"))
        self.toolButton_2.setText(_translate("ReceptionWindow", "Herbergi"))
        self.toolButton_3.setText(_translate("ReceptionWindow", "Nýskrá"))
        self.toolButton_4.setText(_translate("ReceptionWindow", "Pantanir"))
        self.toolButton_5.setText(_translate("ReceptionWindow", "Um mig"))
        self.btnCreateOrder.setText(_translate("ReceptionWindow", "Panta"))
        self.label_7.setText(_translate("ReceptionWindow", "Kennitala"))
        self.label_8.setText(_translate("ReceptionWindow", "Pöntunarnúmer"))
        self.label_6.setText(_translate("ReceptionWindow", "Staðsetning"))
        self.label_10.setText(_translate("ReceptionWindow", "Tegund herbergis"))
        self.label.setText(_translate("ReceptionWindow", "Innskráning"))
        self.label_2.setText(_translate("ReceptionWindow", "Útskráning"))
        self.label_9.setText(_translate("ReceptionWindow", "Room"))
        self.btnFindAvailableRooms.setText(_translate("ReceptionWindow", "Finna laus herbergi"))
        self.btnAddRoomToOrder.setText(_translate("ReceptionWindow", "Bæta við herbergi"))
        self.label_3.setText(_translate("ReceptionWindow", "Fyrranafn*"))
        self.label_11.setText(_translate("ReceptionWindow", "Eftirnafn*"))
        self.label_12.setText(_translate("ReceptionWindow", "Kennitala*"))
        self.label_13.setText(_translate("ReceptionWindow", "Netfang*"))
        self.label_14.setText(_translate("ReceptionWindow", "Sími*"))
        self.label_15.setText(_translate("ReceptionWindow", "Land*"))
        self.label_16.setText(_translate("ReceptionWindow", "Borg/bær*"))
        self.label_17.setText(_translate("ReceptionWindow", "Póstnúmer*"))
        self.label_18.setText(_translate("ReceptionWindow", "Gata*"))
        self.label_19.setText(_translate("ReceptionWindow", "Húsanúmer*"))
        self.label_20.setText(_translate("ReceptionWindow", "Hurð"))
        self.label_21.setText(_translate("ReceptionWindow", "Notandanafn"))
        self.label_22.setText(_translate("ReceptionWindow", "Lykilorð"))
        self.btnRegCus.setText(_translate("ReceptionWindow", "Nýskrá"))
        self.label_4.setText(_translate("ReceptionWindow", "Kennitala"))
        self.btnSearchCusHistory.setText(_translate("ReceptionWindow", "Leita"))
        self.labelAboutWorkplaces.setText(_translate("ReceptionWindow", "Vinnustaður/ir:"))
        self.labelAboutPhone.setText(_translate("ReceptionWindow", "Sími:"))
        self.labelAboutEmail.setText(_translate("ReceptionWindow", "Netfang:"))
        self.labelAboutName.setText(_translate("ReceptionWindow", "Nafn:"))
        self.labelAboutSSN.setText(_translate("ReceptionWindow", "Kennitala:"))
        self.labelAboutAddress.setText(_translate("ReceptionWindow", "Heimilisfang:"))
        self.labelAboutUser.setText(_translate("ReceptionWindow", "Notandanafn:"))
        self.labelAboutTitle.setText(_translate("ReceptionWindow", "Starfsheiti:"))
        self.labelAboutID.setText(_translate("ReceptionWindow", "Auðkenni:"))
        self.labelTopTitle.setText(_translate("ReceptionWindow", "ActionTitle"))
        self.labelTopName.setText(_translate("ReceptionWindow", "Name"))
        self.menuForrit.setTitle(_translate("ReceptionWindow", "Forrit"))
        self.actionSkra_ut.setText(_translate("ReceptionWindow", "Skrá út"))
        self.actionH_tta.setText(_translate("ReceptionWindow", "Hætta"))

import icons_rc
